### ISSUE TITLE
assertion failed

### ISSUE THREAD

**Issue by atrandys** [wangyu-/udp2raw-multiplatform#1]
![image](https://user-images.githubusercontent.com/37266675/41727888-016ea6e6-75a8-11e8-8a12-ea1940ebf2f4.png)
1、win7运行
2、报错如图所示
小白不懂，请大佬赐教。

**Comment by wangyu-** [comment]
windows版的没有`-a`选项。

建议你先过一遍wiki，然后按照这里的操作：
https://github.com/wangyu-/udp2raw-multiplatform/wiki/快速入门

**Comment by atrandys** [comment]
谢谢大佬  我再仔细研究
