### ISSUE TITLE
mac client 每次启动会连接server的随机tcp port

### ISSUE THREAD

**Issue by fbion** [wangyu-/udp2raw-multiplatform#11]
server:
nohup ./udp2raw_amd64 -s -l0.0.0.0:4096  -r127.0.0.1:16824  -k "passwd" --raw-mode faketcp   --cipher-mode xor -a&
client:
udp2raw_mp_nolibnet -c -l0.0.0.0:3333  -rserverip:4096 -k "passwd" --raw-mode faketcp --cipher-mode xor

访问随机端口是在 [2018-09-10 18:01:55][INFO]waiting for a use-able packet to be captured 时开始
每一次启动都不一样
这次是18148 38121

**Comment by wangyu-** [comment]
nolibnet版启动时会向目标ip的一个随机tcp端口发送数据；再用pcap来抓取，来获得link level header。

是符合预期的。
