### ISSUE TITLE
用windows版本的udp2raw打开网页非常慢

### ISSUE THREAD

**Issue by linsongze** [wangyu-/udp2raw-multiplatform#13]
我的之前的网络结构是
浏览器----》kcpclient(自带的socks5&加密，没有用ssr)----》kcpserver.
可以流畅的观看2k的youtube（4M/s）.
使用感觉是秒开google 结果页面。
今天出于好玩，按照教程
在linux安装启动udp2raw-tunnel，windows启动udp2raw_mp_nolibnet.exe（题外话，-l ip:port -r ip:port 选项与参数要有空格）
然后网络结构是浏览器-》kcpclient-》udp2raw_mp_nolibnet-》udp2raw-tunnel-》kcpserver.
启动参数是
./udp2raw_amd64 -s -l0.0.0.0:38080 -r127.0.0.1:28080 -k "ssr" --raw-mode faketcp -a
 .\udp2raw_mp_nolibnet.exe -c -r xxx.xxx.xxx.xxx:38080 -l 0.0.0.0:28080 --raw-mode easy-faketcp -k"ssr"
然后打开浏览器，用google搜索内容，，发现浏览器此时的网速是龟速的....
我是不是哪个参数不对，，还是打开的方式不对....

**Comment by yyysuo** [comment]
udp2raw windows版本在系统睡眠唤醒后进程会自己死掉，任务管理器里面已经看不到这个进程了，但是实际上还会起一定的作用，表现就是通过通道访问网站速度极慢，Youtube只有20K左右的速度。
解决方案是重新运行一下udp2raw_mp_nolibnet.exe，或者在计划任务里面添加一条计划任务，在windows用户登陆时，运行启动脚本。

我用Hiboy的路由器固件集成的Udp2raw，也出现过这种现象。或者是你的网络环境对大量发包做了限制。
