### ISSUE TITLE
第三方openvpn是否可以配合udp2raw+UDPspeeder使用

### ISSUE THREAD

**Issue by huai201208** [wangyu-/udp2raw-multiplatform#14]
目前，朋友推荐了一个国外的VPN厂商，极力推荐他家的隐私保护政策。我也很喜欢这家VPN，但是这家VPN被墙严重。
于是产生想法，是否可以使用一个中转服务器（香港类似），然后本地和服务器上面搭建udp2raw+UDPspeeder。服务器上方将udp2raw的-r参数指向第三方VPN厂商提供VPN的IP地址。不知道是否可行。
目前我的流程是这样的：
A：111.222.333.444 （第三方OPENVPN厂商提供IP）
B：66.77.88.99（我自己的中转服务器）

1、本地监听一个端口转发，比如socat，转发本地1193端口到远程IP111.222.333.444的1194端口（第三方OPENVPN提供的IP和端口）
2、我自己的中转服务器上运行：
./speederv2 -s -l0.0.0.0:20000 -r127.0.0.1:1193 -f10:10 --mode 0 #本地设置的端口转发端口
./udp2raw -s -l0.0.0.0:20001 -r 127.0.0.1:20000  --raw-mode faketcp  -a -k passwd
3、本地客户端运行：
udp2raw_mp.exe -c -r66.77.88.99:20001 -l 127.0.0.1:8855 --raw-mode faketcp -k passwd #已经提前通过 -g 手动管理员模式cmd添加防火墙命令
speederv2.exe -c -l0.0.0.0:3333 -r127.0.0.1:8855 -f10:10 --mode 0 --report 10

然后我通过第三方OPENVPN厂商给我的配置文件，修改里面的IP地址为127.0.0.1端口3333.
然后连接，成功。
但是发现一个问题，不能解析域名，只能通过直接访问IP的形式，发生了什么？

**Comment by wangyu-** [comment]
>于是产生想法，是否可以使用一个中转服务器（香港类似），然后本地和服务器上面搭建udp2raw+UDPspeeder。服务器上方将udp2raw的-r参数指向第三方VPN厂商提供VPN的IP地址。不知道是否可行。

这个是可以的，设计上就是支持的。 我自己也经常这样用。


>1、本地监听一个端口转发，比如socat，转发本地1193端口到远程IP111.222.333.444的1194端口（第三方OPENVPN提供的IP和端口）
2、我自己的中转服务器上运行：
./speederv2 -s -l0.0.0.0:20000 -r127.0.0.1:1193 -f10:10 --mode 0 #本地设置的端口转发端口
./udp2raw -s -l0.0.0.0:20001 -r 127.0.0.1:20000 --raw-mode faketcp -a -k passwd
3、本地客户端运行：
udp2raw_mp.exe -c -r66.77.88.99:20001 -l 127.0.0.1:8855 --raw-mode faketcp -k passwd #已经提前通过 -g 手动管理员模式cmd添加防火墙命令
speederv2.exe -c -l0.0.0.0:3333 -r127.0.0.1:8855 -f10:10 --mode 0 --report 10

没看懂socat是干什么的，貌似是多余的。

>但是发现一个问题，不能解析域名，只能通过直接访问IP的形式，发生了什么？

不清楚了。自己追查一下吧。

**Comment by huai201208** [comment]
谢谢大佬.支持就稳了！
