### ISSUE TITLE
无法启动，自动退出

### ISSUE THREAD

**Issue by Cathgao** [wangyu-/udp2raw-multiplatform#28]
远程服务器已经打开端口，直接用浏览器访问端口也受到请求打印出信息，但win客户端无法启动。
网络环境：二级路由器下
![udpraw](https://user-images.githubusercontent.com/21031564/59192056-d88c7000-8bb3-11e9-9b3b-dfe01f560851.PNG)

**Comment by Cathgao** [comment]
直接运行会找不到任何网卡，右键管理员运行后能正确识别网卡。可能是win10更新后的权限管理变化，希望跟进

**Comment by wangyu-** [comment]
有可能是你在安装npcap时勾选了“只允许管理员权限使用”。（记不清这个选项是否是默认勾选的了

**Comment by Cathgao** [comment]
> 有可能是你在安装npcap时勾选了“只允许管理员权限使用”。（记不清这个选项是否是默认勾选的了

但是我之前都是一直直接用的，也没有给bat或者exe勾选默认管理员权限。中间一段时间没用之后再用发现就这样了
