### ISSUE TITLE
无法控制防火墙的情况下是不是只能用easy-fake模式？

### ISSUE THREAD

**Issue by phc217** [wangyu-/udp2raw-multiplatform#4]
电脑是公司的，受组策略控制强制关闭了防火墙，这种情况是不是不能用普通模式了？

**Comment by wangyu-** [comment]
你也可以试下不加iptables，直接用faketcp模式。 在有些防火墙策略下，不加那些规则，也能用faketcp。 只要server端不提示`RST==1`就没问题。
