### ISSUE TITLE
does FATAL Bad Memory Block. are OK?

### ISSUE THREAD

**Issue by lygstate** [wangyu-/udp2raw-multiplatform#44]
For English speaking user：
https://github.com/wangyu-/UDPspeeder/wiki/Issue-Guide

FATAL Bad Memory Block.
[2020-09-19 02:55:16][INFO](re)sent handshake2
[2020-09-19 02:55:16][INFO]changed state from to client_handshake2 to client_ready
FATAL Bad Memory Block.
FATAL Bad Memory Block.
FATAL Bad Memory Block.
FATAL Bad Memory Block.
FATAL Bad Memory Block.
FATAL Bad Memory Block.
FATAL Bad Memory Block.
FATAL Bad Memory Block.
FATAL Bad Memory Block.
FATAL Bad Memory Block.
FATAL Bad Memory Block.
FATAL Bad Memory Block.
FATAL Bad Memory Block.
FATAL Bad Memory Block.
FATAL Bad Memory Block.
FATAL Bad Memory Block.
FATAL Bad Memory Block.
FATAL Bad Memory Block.
FATAL Bad Memory Block.
FATAL Bad Memory Block.

**Comment by wangyu-** [comment]
Could you please explain a bit on how to pre-produce it?

**Comment by lygstate** [comment]
got the reason， re install ncap driver  solve this
